server {
    listen 80;
    server_name adtechtracker.local;

    root /var/www/adtechtracker.local/public;

    index index.php;

    error_log  /var/www/adtechtracker.local/storage/logs/nginx_error.log;
    access_log /var/www/adtechtracker.local/storage/logs/nginx_access.log;

    location ~* .(jpg|jpeg|gif|css|png|js|ico|html)$ {
        access_log off;
        expires max;
    }

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~* .php$ {
        try_files $uri = 404;
        fastcgi_split_path_info ^(.+.php)(/.+)$;
        fastcgi_pass adtechtracker-php:9000;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        fastcgi_param PATH_INFO $fastcgi_path_info;        
        include fastcgi_params;
    }
}