xdebug.mode=develop,debug
error_reporting = E_ALL
display_errors = On
display_startup_errors = On
log_errors = On
log_errors_max_len = 1024
ignore_repeated_errors = Off
ignore_repeated_source = On
report_memleaks = On
html_errors = Off
error_log = "/var/www/adtechtracker.local/storage/logs/php_error.log"
